In [1]:
from alpha_vantage.fundamentaldata import FundamentalData
from alpha_vantage.timeseries import TimeSeries

ModuleNotFoundError: No module named 'alpha_vantage'

In [20]:
fd = FundamentalData(key='')
ts = TimeSeries(key='')

ts.get_symbol_search(['imb'])

(    1. symbol                                            2. name      3. type  \
 0        IMBI                        iMedia Brands Inc - Class A       Equity
 1     IMB.LON                                Imperial Brands PLC       Equity
 2       IMBAX     VOYA LIMITED MATURITY BOND PORTFOLIO CLASS ADV  Mutual Fund
 3       IMBBF                                Imperial Brands Plc       Equity
 4       IMBBY                                Imperial Brands Plc       Equity
 5       IMBIL                                  iMedia Brands Inc       Equity
 6       IMBIX           DELAWARE IVY MUNICIPAL BOND FUND CLASS I  Mutual Fund
 7    IMBA.LON    iShares US Mortgage Backed Securities UCITS Acc          ETF
 8    IMBE.AMS  iShares US Mortgage Backed Securities UCITS ET...          ETF
 9  IMBB11.SAO                 Etf Bradesco Ima-B Fundo De Indice          ETF

           4. region 5. marketOpen 6. marketClose 7. timezone 8. currency  \
 0     United States         09:30          16:00      UTC-04         USD
 1    United Kingdom         08:00          16:30      UTC+01         GBX
 2     United States         09:30          16:00      UTC-04         USD
 3     United States         09:30          16:00      UTC-04         USD
 4     United States         09:30          16:00      UTC-04         USD
 5     United States         09:30          16:00      UTC-04         USD
 6     United States         09:30          16:00      UTC-04         USD
 7    United Kingdom         08:00          16:30      UTC+01         USD
 8         Amsterdam         09:00          17:40      UTC+01         EUR
 9  Brazil/Sao Paolo         10:00          17:30      UTC-03         BRL

   9. matchScore
 0        0.8571
 1        0.7500
 2        0.7500
 3        0.7500
 4        0.7500
 5        0.7500
 6        0.7500
 7        0.6667
 8        0.6000
 9        0.5000  ,
 None)

In [25]:
inc_stm = fd.get_income_statement_annual('IMB.LON')

ValueError: Error getting data from the api, no return was given.

In [24]:
display(inc_stm[0])

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
0,2022-06-30,USD,135620000000,196109000000,93355000000,62650000000,83383000000,27725000000,24512000000,55217000000,...,12600000000,2980000000,83716000000,10978000000,2063000000,72738000000,66238000000,85779000000,88759000000,72738000000
1,2021-06-30,USD,115856000000,165936000000,79977000000,52232000000,69916000000,25224000000,20716000000,48461000000,...,9300000000,2521000000,71102000000,9831000000,2346000000,61271000000,59897000000,73448000000,75969000000,61271000000
2,2020-06-30,USD,96937000000,140503000000,73159000000,46078000000,52959000000,24709000000,19269000000,46350000000,...,10700000000,2211000000,53036000000,8755000000,2591000000,44281000000,47807000000,55627000000,57838000000,44281000000
3,2019-06-30,USD,82933000000,123495000000,67908000000,42910000000,42959000000,23098000000,16876000000,41874000000,...,9700000000,1900000000,43688000000,4448000000,2686000000,39240000000,41154000000,46374000000,48274000000,39240000000
4,2018-06-30,USD,72007000000,107222000000,62776000000,38353000000,35058000000,22223000000,14726000000,39149000000,...,7700000000,2200000000,36474000000,19903000000,2733000000,16571000000,13715000000,39207000000,41407000000,16571000000